extraction:
  cpp:
    after_prepare: 
      - python report.py 22
  cobol:
    after_prepare: 
      - python report.py 22
  csharp:
    after_prepare: 
      - python report.py 22
  java:
    after_prepare: 
      - python report.py 22
  javascript:
    after_prepare: 
      - python report.py 22
  python:
    after_prepare: 
      - python report.py 22
